Fix indentation

diff --git a/999-build-everything b/999-build-everything
--- a/999-build-everything
+++ b/999-build-everything
@@ -2,39 +2,39 @@
 
 itb_exit() {
     local -i ec=$?
-	if [[ -n "${BASH_VERSION}" ]]; then
+    if [[ -n "${BASH_VERSION}" ]]; then
         local -i n=${#BASH_SOURCE[@]}
         local -r recipe_name="${BASH_SOURCE[n]}"
-	else
-		local -r recipe_name="${ZSH_ARGZERO}"
-	fi
-        echo -n "${recipe_name}: "
-        if (( ec == 0 )); then
-                echo "done!"
-        elif (( ec == ITB_ERR_ARG )); then
-                echo "argument error!"
-        elif (( ec == ITB_ERR_SETUP )); then
-                echo "error in setting everything up!"
-        elif (( ec == ITB_ERR_SYSTEM )); then
-                echo "unexpected system error!"
-        elif (( ec == ITB_ERR_DOWNLOAD )); then
-                echo "error in downloading the source file!"
-        elif (( ec == ITB_ERR_UNTAR )); then
-                echo "error in un-taring the source file!"
-        elif (( ec == ITB_ERR_CONFIGURE )); then
-                echo "error in configuring the software!"
-        elif (( ec == ITB_ERR_MAKE )); then
-                echo "error in compiling the software!"
-        elif (( ec == ITB_ERR_PRE_INSTALL )); then
-                echo "error in pre-installing the software!"
-        elif (( ec == ITB_ERR_INSTALL )); then
-                echo "error in installing the software!"
-        elif (( ec == ITB_ERR_POST_INSTALL )); then
-                echo "error in post-installing the software!"
-        else
-                echo "oops, unknown error!!!"
-        fi
-        exit ${ec}
+    else
+        local -r recipe_name="${ZSH_ARGZERO}"
+    fi
+    echo -n "${recipe_name}: "
+    if (( ec == 0 )); then
+        echo "done!"
+    elif (( ec == ITB_ERR_ARG )); then
+        echo "argument error!"
+    elif (( ec == ITB_ERR_SETUP )); then
+        echo "error in setting everything up!"
+    elif (( ec == ITB_ERR_SYSTEM )); then
+        echo "unexpected system error!"
+    elif (( ec == ITB_ERR_DOWNLOAD )); then
+        echo "error in downloading the source file!"
+    elif (( ec == ITB_ERR_UNTAR )); then
+        echo "error in un-taring the source file!"
+    elif (( ec == ITB_ERR_CONFIGURE )); then
+        echo "error in configuring the software!"
+    elif (( ec == ITB_ERR_MAKE )); then
+        echo "error in compiling the software!"
+    elif (( ec == ITB_ERR_PRE_INSTALL )); then
+        echo "error in pre-installing the software!"
+    elif (( ec == ITB_ERR_INSTALL )); then
+        echo "error in installing the software!"
+    elif (( ec == ITB_ERR_POST_INSTALL )); then
+        echo "error in post-installing the software!"
+    else
+        echo "oops, unknown error!!!"
+    fi
+    exit ${ec}
 }
 
 export -f itb_exit > /dev/null
